### ISSUE TITLE
Link to fifa2019.csv in getting started guide is broken

### ISSUE THREAD

**Issue by bradmonk** [ananas-analytics/ananas-examples#1]
The link to fifa2019.csv in the [getting-started guide](https://ananasanalytics.com/docs/user-guide/getting-started) is broken...

> "Drag & drop the downloaded [fifa2019.csv](https://github.com/ananas-analytics/ananas-examples/raw/master/FifaPlayer2019/fifa2019.csv) file to the File Path settings."

...after ([commit](https://github.com/ananas-analytics/ananas-examples/commit/992f705dde92dc0fe0e7dd9239ee04bb853a37a5?diff=unified#diff-0e773ae05772776f5ba643d54080c8a3)) FifaPlayer2019/fifa2019.csv → Fifa2019/fifa2019.csv

**Comment by bhou** [comment]
The example folder name has been changed from FifaPlayer2019 to Fifa2019 in version 0.8.0, but the doc is out-dated.   Fixed the link with the new example file in Ananas Desktop `docs` branch.
