### ISSUE TITLE
Import of CSV files with seperators other than comma does not work

### ISSUE THREAD

**Issue by rSSi** [ananas-analytics/ananas-examples#2]
When trying to open a regular CSV file that uses ";" as a separator, the import fails to work as expected. A way to define the separating characters would be helpful. Using the comma is problematic, because it is used in text a lot and in German/Austrian/Swiss floating point  numbers: 5.3€ == 5,3€

**Comment by bhou** [comment]
This issue has been fixed and released in release 0.8.2 https://github.com/ananas-analytics/ananas-desktop/releases/tag/v0.8.2

**Comment by rSSi** [comment]
That was quick :) - thank you
